acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('chpass/' , views.chpass, name="chpass")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include('board.urls')),
    path('vote/', include('vote.urls')),
    path('trans/', include('trans.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel , name="cancel"),
    path('create/', views.create, name="create")
]

vote/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")

    def __str__(self):
        return self.subject

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    comment = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.topic}_{self.name}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
# Create your views here.

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        t = Topic(subject=s, content=c, maker=request.user)
        t.save()
        cn = request.POST.getlist("cname")
        cc = request.POST.getlist("ccomm")
        for na, com in zip(cn, cc):
            Choice(topic=t, name=na, comment=com).save()
        return redirect("vote:index")
    return render(request, "vote/create.html")

def cancel(request, tpk):
    u = request.user
    t = Topic.objects.get(id=tpk)
    t.voter.remove(u)
    u.choice_set.get(topic=t).choicer.remove(u)
    return redirect("vote:detail", tpk)


def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect("vote:detail", tpk)



def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t" : t,
        "cset" : c
    }
    return render(request, "vote/detail.html", context)

def index(request):
    t = Topic.objects.all()
    context = {
        "tset" : t
    }
    return render(request, "vote/index.html", context)

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>토픽생성</b></h1>

    <form method="post">
        {% csrf_token %}
        <input type="text" name="sub" class="form-control mt-5" placeholder="주제를 입력하세요">
        <textarea name="con" class="form-control mt-3" placeholder="주제를 설명해주세요" style="height: 180px;"></textarea>

        <div class="text-center mt-4">
            <button type="button" onclick="makecho()" class="btn btn-dark" style="width: 40%;">보기생성</button>
            <button class="btn btn-primary" style="width: 40%;">토픽생성</button>
        </div>

        <div class="row" id="here">
        </div>
    </form>

    <script>
        function makecho(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-sm-4 mt-5");
            n.innerHTML = '<input type="text" name="cname" class="form-control" placeholder="보기이름을 입력하세요">\
                            <textarea class="form-control mt-3" name="ccomm" style="height:150px" placeholder="보기를 설명해주세요">';
            d.appendChild(n);
        }
    </script>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}

    <h1><b>{{ t.subject }}</b></h1>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height: 200px;" disabled>{{ t.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ t.maker.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h4>created by <b>{{user}}</b></h4>
            </div>
        </div>
    </div>

    <hr>

    {% if user in t.voter.all %}
        
        <div class="row">
            {% for i in cset %}
                <div class="col-sm-4 mt-4 text-center">
                    <b>{{i.name}}</b>
                    <div class="progress mt-3">
                        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%">{{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%</div>
                    </div>
                    <div class="mt-3">
                        <textarea class="form-control" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mt-4 text-end">
            <a href="{% url 'vote:cancel' t.id %}"><button class="btn btn-danger btn-lg">무르기</button></a>
            <a href="{% url 'vote:index' %}" class="btn btn-dark btn-lg">뒤로가기</a>
        </div>
       
    {% else %}
        <form method="post" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            <div class="row">
                {% for i in cset %}
                    <div class="col-sm-4 mt-4 text-center">
                        <input type="radio" name="cho" {% if forloop.first %} checked {% endif %} value="{{ i.id }}"> <b>{{i.name}}</b>
                        <div class="mt-3">
                            <textarea class="form-control" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="mt-4 text-end">
                <button class="btn btn-primary btn-lg">투표하기</button>
                <a href="{% url 'vote:index' %}" class="btn btn-dark btn-lg">뒤로가기</a>
            </div>
        </form>
    {% endif %}

{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>투표소</b></h1>

    <div class="text-end">
        <a class="btn btn-dark btn-lg" href="{% url 'vote:create' %}">토픽생성</a>
    </div>

    <div class="row mt-5">

        {% for i in tset %}
            <div class="col-sm-4">
                <div class="card">
                    <img src="{{ i.maker.getpic }}" width="100%" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><b>{{ i.subject }}</b></h5>
                        <p class="card-text">{{ i.content|truncatewords:10 }}</p>
                        {% if user in i.voter.all %}
                            <a href="{% url 'vote:detail' i.id %}" class="btn btn-secondary" style="width: 100%;">결과보기</a>
                        {% else %}
                            <a href="{% url 'vote:detail' i.id %}" class="btn btn-dark" style="width: 100%;">투표하기</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>


{% endblock %}