acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('chpass/' , views.chpass, name="chpass")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include('board.urls')),
    path('vote/', include('vote.urls')),
    path('trans/', include('trans.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to="user/%y/%m")
    comment = models.TextField()
    point = models.IntegerField(default=0)


    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User
from django.contrib import messages
# Create your views here.

def chpass(request):
    u = request.user
    cp = request.POST.get("cpass")
    if check_password(cp, u.password):
        np = request.POST.get("npass")
        u.set_password(np)
        u.save()
        return redirect("acc:login")
    else:
        messages.info(request, "패스워드가 일치하지 않습니다.")
    return redirect("acc:update")


def update(request):
    if request.method == "POST":
        u = request.user
        ue = request.POST.get("umail")
        uc = request.POST.get("ucomm")
        up = request.FILES.get("upic")
        u.email, u.comment = ue, uc
        if up:
            u.pic.delete() 
            u.pic = up
        u.save()
        return redirect("acc:profile")
    return render(request, "acc/update.html")


def delete(request):
    u = request.user
    u.pic.delete()
    u.delete()
    return redirect("acc:index")

def profile(request):
    return render(request, "acc/profile.html")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        try:
            User.objects.create_user(username=un, password=up, comment=uc, pic=pi)
            return redirect("acc:login")
        except:
            messages.info(request, "이미 존재하는 username 을 사용하셨습니다!")
    return render(request, "acc/signup.html")

def userlogout(request):
    logout(request)
    return redirect("acc:index")

def userlogin(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u: # 로그인 성공시
            login(request, u)
            messages.success(request, f"{un}님 환영합니다!")
            return redirect("acc:index")
        else:
            messages.info(request, "계정정보가 일치하지 않습니다.")
    return render(request, "acc/login.html")

def index(request):
    return render(request, "acc/index.html")

templates/acc/index.html
{% extends 'base.html' %}
{% block con %}

    <!-- index.html -->
    {% if user.is_authenticated %}
        <h1><b>{{user}}</b> WELCOME 🎈</h1>
    {% else %}
        <h1>LOGIN FIRST! 🙏🏼</h1>
    {% endif %}
    
{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block con %}

    <!-- login.html -->
    <h1><b>로그인</b></h1>

    <form method="post"> 
        {% csrf_token %}
        <div class="mt-5">
            <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold;">
            <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold;">
        </div>
        <div class="text-end mt-4">
            <button class="btn btn-dark">LOGIN</button>
        </div>
    </form>

{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}

    <!-- profile.html -->
    <h1><b>프로필</b></h1>
    <div class="row">
        <div class="col-sm-7" style="margin: auto;">
            <div class="text-center mt-2">
                <img src="{{user.getpic}}" width="80%">
            </div>
        </div>
        <div class="col-sm-5">
            <div class="mb-3 mt-3">
                <label class="form-label">USERNAME</label>
                <input type="text" value="{{user}}" disabled class="form-control" style="font-weight: bold;">
            </div>
            <div class="mb-3">
                <label class="form-label">POINT</label>
                <input type="text" value="{{user.point}} P" style="font-weight: bold;" disabled class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">EMAIL</label>
                <input type="text" value="{{user.email}}" style="font-weight: bold;" disabled class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">COMMENT</label>
                <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{user.comment}}</textarea>
            </div>
        </div>
    </div>


    <div class="text-end mt-4">
        <a href="{% url 'acc:update' %}"><button class="btn btn-dark">프로필수정</button></a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
            계정삭제
        </button>
    </div>

    <!-- Modal in profile.html -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>계정삭제 알림창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:delete' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="container">
                            <input class="form-control" name="cpass" type="password" placeholder="INPUT CURRENT PASSWORD">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-danger">삭제</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}

    <!-- signup.html -->
    <h1><b>회원가입</b></h1>
        
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" name="uname" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">PASSWORD</label>
            <input type="password" name="upass" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" name="ucomm"></textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">USERPIC</label>
            <input type="file" class="form-control" name="upic">
        </div>
        <div class="mt-4 text-end">
            <button class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
        </div>
    </form>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}

        <!-- update.html -->
    <h1><b>정보수정</b></h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" value="{{user}}" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">EMAIL</label>
            <input type="text" class="form-control" name="umail" value="{{ user.email }}">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" name="ucomm">{{ user.comment }}</textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">USERPIC</label>
            <input type="file" class="form-control" name="upic">
        </div>
        <div class="text-end mt-4">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                패스워드 변경
            </button>
            <a href="#" class="btn btn-dark">수정취소</a>
            <button class="btn btn-dark">프로필수정</button>
        </div>
    </form>

    <!-- Modal in update.html -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>패스워드 변경창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:chpass' %}">
                    {% csrf_token %}
                    <div class="modal-body">    
                        <div class="container mt-5 mb-5 text-center">
                            <input type="password" name="cpass" class="form-control" placeholder="INPUT CURRENT PASSWORD">
                            <input type="password" name="npass" class="form-control mt-3" placeholder="INPUT NEW PASSWORD">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">변경</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}