acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('chpass/' , views.chpass, name="chpass")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey")
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include('board.urls')),
    path('vote/', include('vote.urls')),
    path('trans/', include('trans.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CharField, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return self.subject

class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.board}_{self.replyer}"

board/views.py
import re
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.core.paginator import Paginator
from django.utils import timezone
from django.contrib import messages

def unlikey(request,bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect("board:detail", bpk)

def update(request, bpk):
    b = Board.objects.get(id=bpk)
    
    if b.writer != request.user:
        messages.warning(request, "그러다 너 잡혀감..")
        return redirect("board:index")
        
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s,c
        b.save()
        return redirect("board:detail", bpk)
    
    context = {
        "b" :b 
    }
    return render(request, "board/update.html", context)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, content=c, writer=request.user, pubdate=timezone.now()).save()
        return redirect("board:index")
    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        messages.warning(request, "그러다 잡혀감..")
    return redirect("board:index")

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == request.user:
        r.delete()
    else:
        messages.warning(request, "그러다 잡혀감..")
    return redirect("board:detail", bpk)

def creply(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("com")
    Reply(board=b, replyer=request.user, comment=c, pubdate=timezone.now()).save()
    return redirect("board:detail", bpk)

def index(request):
    pg = request.GET.get("page", 1)
    kw = request.GET.get("kw", "")
    cate = request.GET.get("cate", "")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
    else:
        b = Board.objects.all()

    b = b.order_by("-pubdate")
    
    pag = Paginator(b, 2)
    obj = pag.get_page(pg)
    context = {
        "bset": obj,
        "cate" : cate,
        "kw": kw
    }
    return render(request, "board/index.html", context)

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect("board:detail", bpk)

# Create your views here.
def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    context = {
        "b" : b,
        "rset": r
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <!-- board/create.html -->

    <h1><b>게시글 작성</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" name="sub" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" value="{{ user }}" disabled>
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" name="con" style="height: 150px;"></textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">생성</button>
        </div>
    </form>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>{{ b.subject }}</b></h1>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height: 250px;" disabled>{{ b.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ b.writer.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h5>written by <b>{{ b.writer }}</b></h5>
            </div>
            <div class="text-end mt-2">
                {{ b.pubdate|date:'Y년 n월 d일 / H:i' }}
            </div>
        </div>
    </div>

    <div class="text-end mt-5">
        <a class="btn btn-dark" href="{% url 'board:index' %}">메인</a>
        {% if user == b.writer %}
            <a class="btn btn-secondary" href="{% url 'board:update' b.id %}">수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                삭제
            </button>
        {% endif %}
    </div>

    <div class="text-end mt-3">
        {% if user in b.likey.all %}
            <a class="btn btn-danger btn-sm" href="{% url 'board:unlikey' b.id %}">❌</a>
        {% else %}
            <a class="btn btn-primary btn-sm" href="{% url 'board:likey' b.id %}">👍🏻</a>
        {% endif %}
        
    </div>

    <hr>

    <form method="post" action="{% url 'board:creply' b.id %}">
        {% csrf_token %}
        <div class="row mt-4 mb-5">
            <div class="col-sm-10">
                <input type="text" name="com" class="form-control" placeholder="댓글을 작성해주세요">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-dark" style="width: 100%;">댓글작성</button>
            </div>
        </div>
    </form>


    {% for i in rset %}
        <div class="row mt-5">
            <div class="col-sm-3">
                <img src="{{ i.replyer.getpic }}" width="100%">
                <div class="text-center mt-4">
                    <h5><b>{{ i.replyer }}</b></h5>
                </div>
                <div class="text-end mt-2">
                    <h6><b>{{ i.pubdate|date:'Y년 n월 d일 / H:i'}}</b></h6>
                </div>
            </div>
            <div class="col-sm-9" style="margin: auto;">
                <textarea class="form-control" style="height: 130px;" disabled>{{ i.comment }}</textarea>
                <div class="text-end mt-4">
                    {% if user == i.replyer %}
                        <a href="{% url 'board:dreply' b.id i.id %}"><button class="btn btn-danger">댓글삭제</button></a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% empty %}
        <h4 class="text-center mt-5"><b>첫번째 댓글을 달아주세요 🙏🏻</b></h4>
    {% endfor %}


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ b.subject }} 를 정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                    <a class="btn btn-danger" href="{% url 'board:delete' b.id %}">삭제</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}
    <h1><b>게시판</b></h1>

    <div class="text-end">
        <a class="btn btn-dark" href="{% url 'board:create' %}">게시글작성</a>
    </div>


    <table class="table mt-4 table-hover">
        <thead>
            <tr class="table-dark">
                <th scope="col">순번</th>
                <th scope="col">제목</th>
                <th scope="col">내용</th>
                <th scope="col">작성자</th>
                <th scope="col">좋아요</th>
            </tr>
        </thead>
        <tbody>
            {% for i in bset %}
                <tr>
                    <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                    <td><a href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                    <td>{{ i.content|truncatewords:10 }}</td>
                    <td>{{ i.writer }}</td>
                    <td>{{ i.likey.count }}</td>
                </tr>
            {% empty %}
                <tr>
                    <th colspan="5" class="text-center">
                        {% if kw %}
                            검색결과가 없습니다 ❌
                        {% else %}
                            첫번째 게시글을 작성해주세요 👏
                        {% endif %}
                    </th>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>

    <form>
        <div class="row mt-4 mb-4">
            <div class="col-sm-2">
                <select name="cate" class="form-select">
                    <option value="sub" {% if cate == 'sub' %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == 'wri' %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == 'con' %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-8">
                <input type="text" name="kw" value="{{kw}}" class="form-control">
            </div>
            <div class="col-sm-1">
                <button class="btn btn-dark" style="width: 100%;">검색</button>
            </div>
            <div class="col-sm-1">
                <a href="{% url 'board:index' %}" class="btn btn-dark" style="width: 100%;">리셋</a>
            </div>
        </div>
    </form>



    <nav aria-label="Page navigation example" class="mt-5">
        <ul class="pagination justify-content-center">

            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}

            {% for i in bset.paginator.page_range %}
                {% if bset.number|add:3 >= i and i >= bset.number|sub:2 %}
                    <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}
        </ul>
    </nav>

    <style>
        a {
            text-decoration: none;
            font-weight: bold;
            color: black;
        }
        a:hover {
            color : rgba(255, 0, 0, 0.842);
        }
    </style>




{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <!-- board/update.html -->

    <h1><b>게시글수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" class="form-control" name="sub" value="{{ b.subject }}">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" disabled value="{{ b.writer }}">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" style="height: 150px;" name="con">{{ b.content }}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">수정</button>
        </div> 
    </form>
{% endblock %}